// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import gatherer "github.com/baunes/api-gatherer/gatherer"
import mock "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Get provides a mock function with given fields: _a0
func (_m *Client) Get(_a0 string) (*gatherer.Response, error) {
	ret := _m.Called(_a0)

	var r0 *gatherer.Response
	if rf, ok := ret.Get(0).(func(string) *gatherer.Response); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gatherer.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Query provides a mock function with given fields: _a0, _a1
func (_m *Client) Query(_a0 string, _a1 string) (*gatherer.Response, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *gatherer.Response
	if rf, ok := ret.Get(0).(func(string, string) *gatherer.Response); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gatherer.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
