// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import common "github.com/baunes/api-gatherer/db/common"
import mock "github.com/stretchr/testify/mock"

// DatabaseHelper is an autogenerated mock type for the DatabaseHelper type
type DatabaseHelper struct {
	mock.Mock
}

// Client provides a mock function with given fields:
func (_m *DatabaseHelper) Client() common.ClientHelper {
	ret := _m.Called()

	var r0 common.ClientHelper
	if rf, ok := ret.Get(0).(func() common.ClientHelper); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.ClientHelper)
		}
	}

	return r0
}

// Collection provides a mock function with given fields: name
func (_m *DatabaseHelper) Collection(name string) common.CollectionHelper {
	ret := _m.Called(name)

	var r0 common.CollectionHelper
	if rf, ok := ret.Get(0).(func(string) common.CollectionHelper); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.CollectionHelper)
		}
	}

	return r0
}
